In [7]:
import re

line = '   hi thi4s Is  shalin 3 23, by 34slafd, '
line = re.sub('[^a-zA-Z]+', ' ', line).strip().upper()
# line = line.strip().upper()
print line

HI THI S IS SHALIN BY SLAFD


In [6]:
s = '98273rkjsdfha'
print 'sd' in s
for i in range(1, len(s)):
    print s[i]

True
8
2
7
3
r
k
j
s
d
f
h
a


In [7]:
d = dict()
d[1] = 2
d[2] = 4
d[3] = 1

print len(d)

3


In [15]:
import numpy as np

a = np.zeros(5)
print a
print ord('A') - ord(' ')

[ 0.  0.  0.  0.  0.]
33


In [18]:
print ord('A')
print chr(65)

65
A


In [21]:
dic = dict()
for i in range(26):
    dic[chr(65 + i)] = i
dic[' '] = 26
print dic

{' ': 26, 'A': 0, 'C': 2, 'B': 1, 'E': 4, 'D': 3, 'G': 6, 'F': 5, 'I': 8, 'H': 7, 'K': 10, 'J': 9, 'M': 12, 'L': 11, 'O': 14, 'N': 13, 'Q': 16, 'P': 15, 'S': 18, 'R': 17, 'U': 20, 'T': 19, 'W': 22, 'V': 21, 'Y': 24, 'X': 23, 'Z': 25}


In [22]:
B = np.zeros((27, 2))
B[2, 1] = 1
print B

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


NameError: name 'e' is not defined

In [100]:
import numpy as np
from scipy.misc import logsumexp

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

A = np.dot(a, b)
B = np.multiply(a, b)  # element wise
C = np.array([2, 3])

print A
print B
print C
print '\n'
# # print np.multiply(A, C)
# M = np.log(C)
# N = np.log(np.multiply(A, C))
# # M[1]
# N[0][0]

# D = C[:, np.newaxis]
# print D

# print A + D
print A[:, 1]
print logsumexp(A[:, 1])
print logsumexp(A, axis = 0)
print np.sum(A, axis=1)

[[4 1]
 [2 2]]
[[4 0]
 [0 2]]
[2 3]


[1 2]
2.31326168752
[ 4.12692801  2.31326169]
[5 4]


In [53]:
import numpy as np

l = []
a = np.array([1, 2])
b = np.array([3, 5])
l.append(a)
l.append(b)
print np.matrix(l)

[[1 2]
 [3 5]]


In [64]:
arr = ['A','B','C']
arr.insert(0,'D')
arr.reverse()
print arr

['C', 'B', 'A', 'D']


In [93]:
import numpy as np

a = [[1.0, 0.0], [0.0, 1.0]]
b = [[4.0, 1.0], [2.0, 2.0]]

A = np.dot(a, b)
B = np.multiply(a, b)  # element wise
C = np.array([2.0, 3.0])

print A
print B
print C
print '\n'

D = C[:, np.newaxis]
print D

print A * C
A / 2

print '\n'
print A
print np.sum(A, axis=0) + np.array([4, 7])
# print A / np.sum(A, axis=1)[:, np.newaxis]
# A.shape

np.log(A)

[[ 4.  1.]
 [ 2.  2.]]
[[ 4.  0.]
 [ 0.  2.]]
[ 2.  3.]


[[ 2.]
 [ 3.]]
[[ 8.  3.]
 [ 4.  6.]]


[[ 4.  1.]
 [ 2.  2.]]
[ 10.  10.]


array([[ 1.38629436,  0.        ],
       [ 0.69314718,  0.69314718]])

In [71]:
for i in range(0, 3):
    print i

0
1
2


In [102]:
import numpy as np

l = np.random.dirichlet(np.ones(27),size=1)
print l[0]

[ 0.02312284  0.01062951  0.02664678  0.05175905  0.04480709  0.0272776
  0.00469599  0.0161693   0.00786482  0.04484716  0.00354797  0.00667852
  0.07295409  0.01995659  0.08482007  0.01110972  0.00448074  0.01167143
  0.02017811  0.03238951  0.00637706  0.09611833  0.0350238   0.0028546
  0.1437595   0.04620236  0.14405746]


In [94]:
l = [1, 2, 3, 4]
print l[-1]

4


In [107]:
print 1e-5 + 0.0001

0.00011


In [119]:
import numpy as np

A = [[  2.42995968e-04,   1.22386446e-01],
 [  2.39561379e-02,   4.77556284e-16],
 [  3.86445056e-02,   2.46660729e-05],
 [  7.48992104e-02,   6.69143886e-07],
 [  1.19827010e-06,   2.05229533e-01],
 [  4.28844444e-02,   1.61571568e-18],
 [  2.43660067e-02,   1.68204842e-03],
 [  1.01347900e-01,   9.27182934e-03],
 [  2.12711086e-10,   1.12152623e-01],
 [  1.62665134e-03,   2.12232237e-32],
 [  6.58053955e-03,   4.37985457e-09],
 [  5.28622002e-02,   1.14055540e-02],
 [  4.71728889e-02,   3.78263149e-20],
 [  1.14309018e-01,   2.01778559e-07],
 [  8.39301924e-15,   1.26852935e-01],
 [  2.13094211e-02,   1.63468164e-03],
 [  2.36603832e-03,   9.71521365e-23],
 [  1.04105683e-01,   2.47718013e-09],
 [  1.07432927e-01,   6.94921483e-10],
 [  1.37425390e-01,   7.42933037e-04],
 [  1.23598443e-03,   4.22568466e-02],
 [  2.09246513e-02,   9.37368279e-35],
 [  3.95572031e-02,   1.19095014e-31],
 [  1.48198365e-03,   6.85959322e-05],
 [  3.51930823e-02,   1.68525270e-06],
 [  7.39386972e-05,   2.30633767e-58],
 [  3.41560233e-12,   3.66288745e-01]]

A0 = np.array([a[0] for a in A])
A1 = np.array([a[1] for a in A])

print 'A0:'
sort_index0 = np.argsort(A0)[::-1][:7]
print sort_index0
print [chr(ord('A') + idx) for idx in sort_index0]
print [A0[idx] for idx in sort_index0]
print 'A1:'
sort_index1 = np.argsort(A1)[::-1][:7]
print sort_index1
print [chr(ord('A') + idx) for idx in sort_index1]
print [A1[idx] for idx in sort_index1]


print '\n'
print A0
print A1

A0:
[19 13 18 17  7  3 11]
['T', 'N', 'S', 'R', 'H', 'D', 'L']
[0.13742539000000001, 0.114309018, 0.107432927, 0.104105683, 0.1013479, 0.074899210399999999, 0.052862200200000001]
A1:
[26  4 14  0  8 20 11]
['[', 'E', 'O', 'A', 'I', 'U', 'L']
[0.36628874500000003, 0.20522953299999999, 0.126852935, 0.122386446, 0.11215262300000001, 0.042256846600000002, 0.011405554]


[  2.42995968e-04   2.39561379e-02   3.86445056e-02   7.48992104e-02
   1.19827010e-06   4.28844444e-02   2.43660067e-02   1.01347900e-01
   2.12711086e-10   1.62665134e-03   6.58053955e-03   5.28622002e-02
   4.71728889e-02   1.14309018e-01   8.39301924e-15   2.13094211e-02
   2.36603832e-03   1.04105683e-01   1.07432927e-01   1.37425390e-01
   1.23598443e-03   2.09246513e-02   3.95572031e-02   1.48198365e-03
   3.51930823e-02   7.39386972e-05   3.41560233e-12]
[  1.22386446e-01   4.77556284e-16   2.46660729e-05   6.69143886e-07
   2.05229533e-01   1.61571568e-18   1.68204842e-03   9.27182934e-03
   1.12152623e-01   2.1223