In [7]:
import re

line = '   hi thi4s Is  shalin 3 23, by 34slafd, '
line = re.sub('[^a-zA-Z]+', ' ', line).strip().upper()
# line = line.strip().upper()
print line

HI THI S IS SHALIN BY SLAFD


In [6]:
s = '98273rkjsdfha'
print 'sd' in s
for i in range(1, len(s)):
    print s[i]

True
8
2
7
3
r
k
j
s
d
f
h
a


In [7]:
d = dict()
d[1] = 2
d[2] = 4
d[3] = 1

print len(d)

3


In [15]:
import numpy as np

a = np.zeros(5)
print a
print ord('A') - ord(' ')

[ 0.  0.  0.  0.  0.]
33


In [18]:
print ord('A')
print chr(65)

65
A


In [21]:
dic = dict()
for i in range(26):
    dic[chr(65 + i)] = i
dic[' '] = 26
print dic

{' ': 26, 'A': 0, 'C': 2, 'B': 1, 'E': 4, 'D': 3, 'G': 6, 'F': 5, 'I': 8, 'H': 7, 'K': 10, 'J': 9, 'M': 12, 'L': 11, 'O': 14, 'N': 13, 'Q': 16, 'P': 15, 'S': 18, 'R': 17, 'U': 20, 'T': 19, 'W': 22, 'V': 21, 'Y': 24, 'X': 23, 'Z': 25}


In [22]:
B = np.zeros((27, 2))
B[2, 1] = 1
print B

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


NameError: name 'e' is not defined

In [100]:
import numpy as np
from scipy.misc import logsumexp

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

A = np.dot(a, b)
B = np.multiply(a, b)  # element wise
C = np.array([2, 3])

print A
print B
print C
print '\n'
# # print np.multiply(A, C)
# M = np.log(C)
# N = np.log(np.multiply(A, C))
# # M[1]
# N[0][0]

# D = C[:, np.newaxis]
# print D

# print A + D
print A[:, 1]
print logsumexp(A[:, 1])
print logsumexp(A, axis = 0)
print np.sum(A, axis=1)

[[4 1]
 [2 2]]
[[4 0]
 [0 2]]
[2 3]


[1 2]
2.31326168752
[ 4.12692801  2.31326169]
[5 4]


In [53]:
import numpy as np

l = []
a = np.array([1, 2])
b = np.array([3, 5])
l.append(a)
l.append(b)
print np.matrix(l)

[[1 2]
 [3 5]]


In [64]:
arr = ['A','B','C']
arr.insert(0,'D')
arr.reverse()
print arr

['C', 'B', 'A', 'D']


In [93]:
import numpy as np

a = [[1.0, 0.0], [0.0, 1.0]]
b = [[4.0, 1.0], [2.0, 2.0]]

A = np.dot(a, b)
B = np.multiply(a, b)  # element wise
C = np.array([2.0, 3.0])

print A
print B
print C
print '\n'

D = C[:, np.newaxis]
print D

print A * C
A / 2

print '\n'
print A
print np.sum(A, axis=0) + np.array([4, 7])
# print A / np.sum(A, axis=1)[:, np.newaxis]
# A.shape

np.log(A)

[[ 4.  1.]
 [ 2.  2.]]
[[ 4.  0.]
 [ 0.  2.]]
[ 2.  3.]


[[ 2.]
 [ 3.]]
[[ 8.  3.]
 [ 4.  6.]]


[[ 4.  1.]
 [ 2.  2.]]
[ 10.  10.]


array([[ 1.38629436,  0.        ],
       [ 0.69314718,  0.69314718]])

In [71]:
for i in range(0, 3):
    print i

0
1
2


In [92]:
import numpy as np

print np.random.dirichlet(np.ones(27),size=1)

[[ 0.14051924  0.00664426  0.02277217  0.00021809  0.02657583  0.00470169
   0.01556689  0.03248688  0.09182782  0.0135339   0.00550106  0.06321735
   0.01056519  0.06340131  0.00217979  0.03695537  0.09980184  0.01994291
   0.05285106  0.04548011  0.04521446  0.05977286  0.05502936  0.0570045
   0.0026755   0.00543058  0.02012997]]


In [94]:
l = [1, 2, 3, 4]
print l[-1]

4
